/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA tySequence__48JTohSgTy339bRxHzUD8KA;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA_Content tySequence__48JTohSgTy339bRxHzUD8KA_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__48JTohSgTy339bRxHzUD8KA {
  NI len; tySequence__48JTohSgTy339bRxHzUD8KA_Content* p;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};


#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(tySequence__48JTohSgTy339bRxHzUD8KA, newSeq__pureZunicode_3958)(NI len);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZunicode_3967)(tySequence__48JTohSgTy339bRxHzUD8KA* x, NI32 value);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NIMCALL(tySequence__48JTohSgTy339bRxHzUD8KA, toRunes__pureZunicode_3943)(NimStringV2 s) {
	tySequence__48JTohSgTy339bRxHzUD8KA result;
	result.len = 0; result.p = NIM_NIL;
	result = newSeq__pureZunicode_3958(((NI) 0));
	{
		NI32 r;
		NI i;
		NI32 result_2;
		r = (NI32)0;
		i = ((NI) 0);
		result_2 = (NI32)0;
		{
			while (1) {
				NI32 colontmpD_;
				if (!(i < s.len)) goto LA3;
				colontmpD_ = (NI32)0;
				{
					if (!((NU32)(((NU) (((NU8)(s.p->data[i]))))) <= (NU32)(((NU) 127)))) goto LA6_;
					result_2 = ((NI32) (((NU) (((NU8)(s.p->data[i]))))));
					i += ((NI) 1);
				}
				goto LA4_;
				LA6_: ;
				{
					if (!((NU)((NU32)(((NU) (((NU8)(s.p->data[i]))))) >> (NU32)(((NI) 5))) == ((NU) 6))) goto LA9_;
					{
						if (!(i <= (NI)(s.len - ((NI) 2)))) goto LA13_;
						result_2 = ((NI32) ((NU)((NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[i])))) & ((NU) 31))) << (NU32)(((NI) 6))) | (NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 1))])))) & ((NU) 63)))));
						i += ((NI) 2);
					}
					goto LA11_;
					LA13_: ;
					{
						result_2 = ((NI32) 65533);
						i += ((NI) 1);
					}
					LA11_: ;
				}
				goto LA4_;
				LA9_: ;
				{
					if (!((NU)((NU32)(((NU) (((NU8)(s.p->data[i]))))) >> (NU32)(((NI) 4))) == ((NU) 14))) goto LA17_;
					{
						if (!(i <= (NI)(s.len - ((NI) 3)))) goto LA21_;
						result_2 = ((NI32) ((NU)((NU)((NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[i])))) & ((NU) 15))) << (NU32)(((NI) 12))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 1))])))) & ((NU) 63))) << (NU32)(((NI) 6)))) | (NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 2))])))) & ((NU) 63)))));
						i += ((NI) 3);
					}
					goto LA19_;
					LA21_: ;
					{
						result_2 = ((NI32) 65533);
						i += ((NI) 1);
					}
					LA19_: ;
				}
				goto LA4_;
				LA17_: ;
				{
					if (!((NU)((NU32)(((NU) (((NU8)(s.p->data[i]))))) >> (NU32)(((NI) 3))) == ((NU) 30))) goto LA25_;
					{
						if (!(i <= (NI)(s.len - ((NI) 4)))) goto LA29_;
						result_2 = ((NI32) ((NU)((NU)((NU)((NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[i])))) & ((NU) 7))) << (NU32)(((NI) 18))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 1))])))) & ((NU) 63))) << (NU32)(((NI) 12)))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 2))])))) & ((NU) 63))) << (NU32)(((NI) 6)))) | (NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 3))])))) & ((NU) 63)))));
						i += ((NI) 4);
					}
					goto LA27_;
					LA29_: ;
					{
						result_2 = ((NI32) 65533);
						i += ((NI) 1);
					}
					LA27_: ;
				}
				goto LA4_;
				LA25_: ;
				{
					if (!((NU)((NU32)(((NU) (((NU8)(s.p->data[i]))))) >> (NU32)(((NI) 2))) == ((NU) 62))) goto LA33_;
					{
						if (!(i <= (NI)(s.len - ((NI) 5)))) goto LA37_;
						result_2 = ((NI32) ((NU)((NU)((NU)((NU)((NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[i])))) & ((NU) 3))) << (NU32)(((NI) 24))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 1))])))) & ((NU) 63))) << (NU32)(((NI) 18)))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 2))])))) & ((NU) 63))) << (NU32)(((NI) 12)))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 3))])))) & ((NU) 63))) << (NU32)(((NI) 6)))) | (NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 4))])))) & ((NU) 63)))));
						i += ((NI) 5);
					}
					goto LA35_;
					LA37_: ;
					{
						result_2 = ((NI32) 65533);
						i += ((NI) 1);
					}
					LA35_: ;
				}
				goto LA4_;
				LA33_: ;
				{
					if (!((NU)((NU32)(((NU) (((NU8)(s.p->data[i]))))) >> (NU32)(((NI) 1))) == ((NU) 126))) goto LA41_;
					{
						if (!(i <= (NI)(s.len - ((NI) 6)))) goto LA45_;
						result_2 = ((NI32) ((NU)((NU)((NU)((NU)((NU)((NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[i])))) & ((NU) 1))) << (NU32)(((NI) 30))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 1))])))) & ((NU) 63))) << (NU32)(((NI) 24)))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 2))])))) & ((NU) 63))) << (NU32)(((NI) 18)))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 3))])))) & ((NU) 63))) << (NU32)(((NI) 12)))) | (NU)((NU32)((NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 4))])))) & ((NU) 63))) << (NU32)(((NI) 6)))) | (NU)(((NU) (((NU8)(s.p->data[(NI)(i + ((NI) 5))])))) & ((NU) 63)))));
						i += ((NI) 6);
					}
					goto LA43_;
					LA45_: ;
					{
						result_2 = ((NI32) 65533);
						i += ((NI) 1);
					}
					LA43_: ;
				}
				goto LA4_;
				LA41_: ;
				{
					result_2 = ((NI32) (((NU) (((NU8)(s.p->data[i]))))));
					i += ((NI) 1);
				}
				LA4_: ;
				r = result_2;
				colontmpD_ = r;
				add__pureZunicode_3967((&result), colontmpD_);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunicode_626)(tySequence__48JTohSgTy339bRxHzUD8KA* dest) {
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(NI32));
}
}
