/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA tySequence__48JTohSgTy339bRxHzUD8KA;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA_Content tySequence__48JTohSgTy339bRxHzUD8KA_Content;
typedef struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyTuple__BUNQL5x2cKJaBSzOn5pwkg;
typedef struct tySequence__uAVKDgsmtx5N16UbHJVmFg tySequence__uAVKDgsmtx5N16UbHJVmFg;
typedef struct tySequence__uAVKDgsmtx5N16UbHJVmFg_Content tySequence__uAVKDgsmtx5N16UbHJVmFg_Content;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__48JTohSgTy339bRxHzUD8KA {
  NI len; tySequence__48JTohSgTy339bRxHzUD8KA_Content* p;
};
struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg {
NI32 Field0;
NI32 Field1;
};
struct tySequence__uAVKDgsmtx5N16UbHJVmFg {
  NI len; tySequence__uAVKDgsmtx5N16UbHJVmFg_Content* p;
};
typedef tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyArray__9ckaJGbHdUYbig9c7o9aNWT9aA[316];


#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__uAVKDgsmtx5N16UbHJVmFg_Content_PP
#define tySequence__uAVKDgsmtx5N16UbHJVmFg_Content_PP
struct tySequence__uAVKDgsmtx5N16UbHJVmFg_Content { NI cap; tyTuple__BUNQL5x2cKJaBSzOn5pwkg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(tySequence__48JTohSgTy339bRxHzUD8KA, toRunes__pureZunicode_3943)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(NI, wcwidth__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_20)(NI32 c, NIM_BOOL ambiguousIsWide);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, bisearch__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_9)(NI32 ucs, tyTuple__BUNQL5x2cKJaBSzOn5pwkg* table, NI tableLen_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunicode_626)(tySequence__48JTohSgTy339bRxHzUD8KA* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_CONST tySequence__uAVKDgsmtx5N16UbHJVmFg TABLE_F_W__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_5;
extern NIM_CONST tySequence__uAVKDgsmtx5N16UbHJVmFg TABLE_A__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_10;
extern NIM_CONST tyArray__9ckaJGbHdUYbig9c7o9aNWT9aA TABLE_COM__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZcombining95table_1;
extern NIM_BOOL nimInErrorMode__system_3500;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, bisearch__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_9)(NI32 ucs, tyTuple__BUNQL5x2cKJaBSzOn5pwkg* table, NI tableLen_0) {
	NIM_BOOL result;
	NI max;
	NI min;
	NI mid;
{	result = (NIM_BOOL)0;
	max = (NI)(tableLen_0 - ((NI) 1));
	min = ((NI) 0);
	mid = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ucs < table[((NI) 0)].Field0);
		if (T3_) goto LA4_;
		T3_ = (table[max].Field1 < ucs);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA5_: ;
	{
		while (1) {
			if (!(min <= max)) goto LA8;
			mid = (NI)((NI)(min + max) / ((NI) 2));
			{
				if (!(table[mid].Field1 < ucs)) goto LA11_;
				min = (NI)(mid + ((NI) 1));
			}
			goto LA9_;
			LA11_: ;
			{
				if (!(ucs < table[mid].Field0)) goto LA14_;
				max = (NI)(mid - ((NI) 1));
			}
			goto LA9_;
			LA14_: ;
			{
				result = NIM_TRUE;
				goto BeforeRet_;
			}
			LA9_: ;
		} LA8: ;
	}
	result = NIM_FALSE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, wcwidth__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_20)(NI32 c, NIM_BOOL ambiguousIsWide) {
	NI result;
	NI32 ucs;
	NIM_BOOL T29_;
	NIM_BOOL T31_;
	NIM_BOOL T32_;
	NIM_BOOL T33_;
	NIM_BOOL T34_;
	NIM_BOOL T35_;
	NIM_BOOL T36_;
	NIM_BOOL T37_;
	NIM_BOOL T38_;
	NIM_BOOL T39_;
	NIM_BOOL T40_;
	NIM_BOOL T41_;
	NIM_BOOL T45_;
	NIM_BOOL T46_;
	NIM_BOOL T50_;
	NIM_BOOL T53_;
	NIM_BOOL T56_;
	NIM_BOOL T59_;
	NIM_BOOL T62_;
	NIM_BOOL T65_;
	NIM_BOOL T68_;
	NIM_BOOL T71_;
{	result = (NI)0;
	ucs = c;
	{
		if (!(ucs == ((NI32) 0))) goto LA3_;
		result = ((NI) 0);
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T9_;
		T7_ = (NIM_BOOL)0;
		T7_ = (ucs < ((NI32) 32));
		if (T7_) goto LA8_;
		T9_ = (NIM_BOOL)0;
		T9_ = (((NI32) 127) <= ucs);
		if (!(T9_)) goto LA10_;
		T9_ = (ucs < ((NI32) 160));
		LA10_: ;
		T7_ = T9_;
		LA8_: ;
		if (!T7_) goto LA11_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA11_: ;
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = bisearch__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_9(ucs, ((TABLE_F_W__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_5).p) ? (TABLE_F_W__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_5.p->data) : NIM_NIL, TABLE_F_W__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_5.len);
		if (!T15_) goto LA16_;
		result = ((NI) 2);
		goto BeforeRet_;
	}
	LA16_: ;
	{
		NIM_BOOL T20_;
		T20_ = (NIM_BOOL)0;
		T20_ = ambiguousIsWide;
		if (!(T20_)) goto LA21_;
		T20_ = bisearch__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_9(ucs, ((TABLE_A__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_10).p) ? (TABLE_A__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_10.p->data) : NIM_NIL, TABLE_A__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZwc95table_10.len);
		LA21_: ;
		if (!T20_) goto LA22_;
		result = ((NI) 2);
		goto BeforeRet_;
	}
	LA22_: ;
	{
		NIM_BOOL T26_;
		T26_ = (NIM_BOOL)0;
		T26_ = bisearch__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_9(ucs, TABLE_COM__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250ZwcwidthZcombining95table_1, 316);
		if (!T26_) goto LA27_;
		result = ((NI) 0);
		goto BeforeRet_;
	}
	LA27_: ;
	T29_ = (NIM_BOOL)0;
	T29_ = (((NI32) 4352) <= ucs);
	if (!(T29_)) goto LA30_;
	T31_ = (NIM_BOOL)0;
	T32_ = (NIM_BOOL)0;
	T33_ = (NIM_BOOL)0;
	T34_ = (NIM_BOOL)0;
	T35_ = (NIM_BOOL)0;
	T36_ = (NIM_BOOL)0;
	T37_ = (NIM_BOOL)0;
	T38_ = (NIM_BOOL)0;
	T39_ = (NIM_BOOL)0;
	T40_ = (NIM_BOOL)0;
	T41_ = (NIM_BOOL)0;
	T41_ = (ucs <= ((NI32) 4447));
	if (T41_) goto LA42_;
	T41_ = (ucs == ((NI32) 9001));
	LA42_: ;
	T40_ = T41_;
	if (T40_) goto LA43_;
	T40_ = (ucs == ((NI32) 9002));
	LA43_: ;
	T39_ = T40_;
	if (T39_) goto LA44_;
	T45_ = (NIM_BOOL)0;
	T46_ = (NIM_BOOL)0;
	T46_ = (((NI32) 11904) <= ucs);
	if (!(T46_)) goto LA47_;
	T46_ = (ucs <= ((NI32) 42191));
	LA47_: ;
	T45_ = T46_;
	if (!(T45_)) goto LA48_;
	T45_ = !((ucs == ((NI32) 12351)));
	LA48_: ;
	T39_ = T45_;
	LA44_: ;
	T38_ = T39_;
	if (T38_) goto LA49_;
	T50_ = (NIM_BOOL)0;
	T50_ = (((NI32) 44032) <= ucs);
	if (!(T50_)) goto LA51_;
	T50_ = (ucs <= ((NI32) 55203));
	LA51_: ;
	T38_ = T50_;
	LA49_: ;
	T37_ = T38_;
	if (T37_) goto LA52_;
	T53_ = (NIM_BOOL)0;
	T53_ = (((NI32) 63744) <= ucs);
	if (!(T53_)) goto LA54_;
	T53_ = (ucs <= ((NI32) 64255));
	LA54_: ;
	T37_ = T53_;
	LA52_: ;
	T36_ = T37_;
	if (T36_) goto LA55_;
	T56_ = (NIM_BOOL)0;
	T56_ = (((NI32) 65040) <= ucs);
	if (!(T56_)) goto LA57_;
	T56_ = (ucs <= ((NI32) 65049));
	LA57_: ;
	T36_ = T56_;
	LA55_: ;
	T35_ = T36_;
	if (T35_) goto LA58_;
	T59_ = (NIM_BOOL)0;
	T59_ = (((NI32) 65072) <= ucs);
	if (!(T59_)) goto LA60_;
	T59_ = (ucs <= ((NI32) 65135));
	LA60_: ;
	T35_ = T59_;
	LA58_: ;
	T34_ = T35_;
	if (T34_) goto LA61_;
	T62_ = (NIM_BOOL)0;
	T62_ = (((NI32) 65280) <= ucs);
	if (!(T62_)) goto LA63_;
	T62_ = (ucs <= ((NI32) 65376));
	LA63_: ;
	T34_ = T62_;
	LA61_: ;
	T33_ = T34_;
	if (T33_) goto LA64_;
	T65_ = (NIM_BOOL)0;
	T65_ = (((NI32) 65504) <= ucs);
	if (!(T65_)) goto LA66_;
	T65_ = (ucs <= ((NI32) 65510));
	LA66_: ;
	T33_ = T65_;
	LA64_: ;
	T32_ = T33_;
	if (T32_) goto LA67_;
	T68_ = (NIM_BOOL)0;
	T68_ = (((NI32) 131072) <= ucs);
	if (!(T68_)) goto LA69_;
	T68_ = (ucs <= ((NI32) 196605));
	LA69_: ;
	T32_ = T68_;
	LA67_: ;
	T31_ = T32_;
	if (T31_) goto LA70_;
	T71_ = (NIM_BOOL)0;
	T71_ = (((NI32) 196608) <= ucs);
	if (!(T71_)) goto LA72_;
	T71_ = (ucs <= ((NI32) 262141));
	LA72_: ;
	T31_ = T71_;
	LA70_: ;
	T29_ = T31_;
	LA30_: ;
	result = (NI)(((NI) 1) + ((NI) (T29_)));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3500);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, wcswidth__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_34)(NimStringV2 str, NIM_BOOL ambiguousIsWide) {
	NI result;
	tySequence__48JTohSgTy339bRxHzUD8KA splitStr;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	splitStr.len = 0; splitStr.p = NIM_NIL;
	splitStr = toRunes__pureZunicode_3943(str);
	{
		NI32* c;
		NI i;
		NI L;
		NI T3_;
		c = (NI32*)0;
		i = ((NI) 0);
		T3_ = splitStr.len;
		L = T3_;
		{
			while (1) {
				NI w;
				if (!(i < L)) goto LA5;
				c = (&splitStr.p->data[i]);
				w = wcwidth__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_20((*c), ambiguousIsWide);
				{
					if (!(w < ((NI) 0))) goto LA8_;
					result = ((NI) -1);
					eqdestroy___pureZunicode_626((&splitStr));
					goto BeforeRet_;
				}
				goto LA6_;
				LA8_: ;
				{
					result += w;
				}
				LA6_: ;
				i += ((NI) 1);
			} LA5: ;
		}
	}
	{
		LA1_:;
	}
	{
		eqdestroy___pureZunicode_626((&splitStr));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
