/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct Exception Exception;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA tySequence__48JTohSgTy339bRxHzUD8KA;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA_Content tySequence__48JTohSgTy339bRxHzUD8KA_Content;
typedef struct tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg;
typedef struct tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw;
typedef struct tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw) (Exception* e);
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef N_NIMCALL_PTR(void, tyProc__W6IXMh2CA4X1rFYGjUb4yg) (NimStringV2 msg);
struct tySequence__48JTohSgTy339bRxHzUD8KA {
  NI len; tySequence__48JTohSgTy339bRxHzUD8KA_Content* p;
};
struct tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg {
NI len;
tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw* p;
};
struct tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw {
NI cap;
NI32 data[SEQ_DECL_SIZE];
};
struct tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw {
NI cap;
};
typedef NIM_CHAR tyArray__gpc2RrLEcWgv7ONpLYNHOw[2001];
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
typedef N_NIMCALL_PTR(void, tyProc__4SVlZZPmetqBimNsH9cHcOA) (void* p);


#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, initStackBottom)(void);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZunicode_3946)(tySequence__48JTohSgTy339bRxHzUD8KA* s, NI len);
N_LIB_PRIVATE N_NIMCALL(void, shrink__pureZunicode_646)(tySequence__48JTohSgTy339bRxHzUD8KA* x, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZunicode_639)(tySequence__48JTohSgTy339bRxHzUD8KA* s, NI newlen);
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(NI, align__system_1616)(NI address, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc0__system_1891)(NI size, NI align);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_1727)(NI size);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(NI, resize__system_2171)(NI old);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, alignedRealloc0__system_1911)(void* p, NI oldSize, NI newSize, NI align);
N_LIB_PRIVATE N_NOCONV(void*, realloc0Impl__system_1734)(void* p, NI oldSize, NI newSize);
N_LIB_PRIVATE N_NOCONV(void*, reallocImpl__system_1731)(void* p, NI newSize);
static N_INLINE(void, zeroMem__system_1706)(void* p, NI size);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc__system_1865)(NI size, NI align);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1725)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__system_1729)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__system_3489)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledErrorAux__system_3386)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_3357)(tySequence__uB9b75OUPRENsBAu4AnoePA stackTraceEntries);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, add__system_2856)(NimStringV2* x, NCSTRING y);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_180)(NimStringV2* result, NI x);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_158)(NimStringV2* result, NI64 x);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_2650)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__system_3172)(NCSTRING data, NI length);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3245)(Exception** dest, Exception* src);
static N_INLINE(void, nimIncRef)(void* p);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__system_3167)(NCSTRING msg, NI length);
static N_INLINE(void, rawWriteString)(FILE* f, NCSTRING s, NI length);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3248)(Exception** dest, Exception* src);
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_2 = { 17 | NIM_STRLIT_FLAG, "[[reraised from:\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_3 = {17, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_2};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_4 = { 3 | NIM_STRLIT_FLAG, "]]\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_5 = {3, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_6 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_7 = {1, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_8 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_9 = {2, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_10 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_11 = {1, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_12 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_13 = {1, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_12};
N_LIB_PRIVATE NI nim_program_result;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__system_2839;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__system_2842;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__system_2844;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook__system_2847;
N_LIB_PRIVATE Exception* currException__system_3202;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg errorMessageWriter__system_3164;
N_LIB_PRIVATE TFrame* framePtr__system_3200;
N_LIB_PRIVATE TSafePoint* excHandler__system_3201;
N_LIB_PRIVATE GcFrameHeader* gcFramePtr__system_3203;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg onUnhandledException__system_3385;
N_LIB_PRIVATE NIM_BOOL nimInErrorMode__system_3500;
static N_INLINE(void, initStackBottom)(void) {
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__pureZunicode_646)(tySequence__48JTohSgTy339bRxHzUD8KA* x, NI newLen) {
	(*((tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg*) (x))).len = ((NI) (newLen));
}
N_LIB_PRIVATE N_NIMCALL(NI, align__system_1616)(NI address, NI alignment) {
	NI result;
	result = (NI)0;
	{
		if (!(alignment == ((NI) 0))) goto LA3_;
		result = address;
	}
	goto LA1_;
	LA3_: ;
	{
		result = (NI)((NI)(address + (NI)(alignment - ((NI) 1))) & (NI)((NU32) ~((NI)(alignment - ((NI) 1)))));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_1727)(NI size) {
	void* result;
	result = (void*)0;
	result = calloc(((size_t) (size)), ((size_t) 1));
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc0__system_1891)(NI size, NI align) {
	void* result;
	result = (void*)0;
	{
		if (!(((NI) (align)) <= ((NI) 8))) goto LA3_;
		result = alloc0Impl__system_1727(size);
	}
	goto LA1_;
	LA3_: ;
	{
		void* base;
		NI offset;
		NI T6_;
		NI T7_;
		base = alloc0Impl__system_1727(((NI) ((NI)((NI)((NI)(((NI) (size)) + ((NI) (align))) - ((NI) 1)) + ((NI) 2)))));
		offset = (NI)(((NI) (align)) - (NI)(((NI) (ptrdiff_t) (base)) & (NI)(((NI) (align)) - ((NI) 1))));
		T6_ = (NI)0;
		T6_ = pluspercent___system_696(((NI) (ptrdiff_t) (base)), (NI)(offset - ((NI) 2)));
		(*((NU16*) (((void*) (T6_))))) = ((NU16) (offset));
		T7_ = (NI)0;
		T7_ = pluspercent___system_696(((NI) (ptrdiff_t) (base)), offset);
		result = ((void*) (T7_));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign) {
	void* result;
	result = (void*)0;
	{
		tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* p;
		NI T5_;
		void* T6_;
		if (!(((NI) 0) < cap)) goto LA3_;
		T5_ = (NI)0;
		T5_ = align__system_1616(((NI) 4), elemAlign);
		T6_ = (void*)0;
		T6_ = alignedAlloc0__system_1891(((NI) ((NI)(T5_ + (NI)(cap * elemSize)))), ((NI) (elemAlign)));
		p = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T6_));
		(*p).cap = cap;
		result = ((void*) (p));
	}
	goto LA1_;
	LA3_: ;
	{
		result = NIM_NIL;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, resize__system_2171)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
N_LIB_PRIVATE N_NOCONV(void*, reallocImpl__system_1731)(void* p, NI newSize) {
	void* result;
	result = (void*)0;
	result = realloc(p, ((size_t) (newSize)));
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, zeroMem__system_1706)(void* p, NI size) {
	nimZeroMem(p, size);
}
N_LIB_PRIVATE N_NOCONV(void*, realloc0Impl__system_1734)(void* p, NI oldSize, NI newSize) {
	void* result;
	result = (void*)0;
	result = reallocImpl__system_1731(p, ((NI) (((size_t) (newSize)))));
	{
		if (!(((NI) (oldSize)) < ((NI) (newSize)))) goto LA3_;
		zeroMem__system_1706(((void*) ((NI)(((NI) (ptrdiff_t) (result)) + ((NI) (oldSize))))), ((NI) ((NI)(((NI) (newSize)) - ((NI) (oldSize))))));
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1725)(NI size) {
	void* result;
	result = (void*)0;
	result = malloc(((size_t) (size)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc__system_1865)(NI size, NI align) {
	void* result;
	result = (void*)0;
	{
		if (!(((NI) (align)) <= ((NI) 8))) goto LA3_;
		result = allocImpl__system_1725(size);
	}
	goto LA1_;
	LA3_: ;
	{
		void* base;
		NI offset;
		NI T6_;
		NI T7_;
		base = allocImpl__system_1725(((NI) ((NI)((NI)((NI)(((NI) (size)) + ((NI) (align))) - ((NI) 1)) + ((NI) 2)))));
		offset = (NI)(((NI) (align)) - (NI)(((NI) (ptrdiff_t) (base)) & (NI)(((NI) (align)) - ((NI) 1))));
		T6_ = (NI)0;
		T6_ = pluspercent___system_696(((NI) (ptrdiff_t) (base)), (NI)(offset - ((NI) 2)));
		(*((NU16*) (((void*) (T6_))))) = ((NU16) (offset));
		T7_ = (NI)0;
		T7_ = pluspercent___system_696(((NI) (ptrdiff_t) (base)), offset);
		result = ((void*) (T7_));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__system_1729)(void* p) {
	free(p);
}
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p) {
	deallocImpl__system_1729(p);
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align) {
	{
		if (!(align <= ((NI) 8))) goto LA3_;
		dealloc(p);
	}
	goto LA1_;
	LA3_: ;
	{
		NU16 offset;
		NI T6_;
		NI T7_;
		T6_ = (NI)0;
		T6_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 2));
		offset = (*((NU16*) (((void*) (T6_)))));
		T7_ = (NI)0;
		T7_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) (offset)));
		dealloc(((void*) (T7_)));
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void*, alignedRealloc0__system_1911)(void* p, NI oldSize, NI newSize, NI align) {
	void* result;
	result = (void*)0;
	{
		if (!(((NI) (align)) <= ((NI) 8))) goto LA3_;
		result = realloc0Impl__system_1734(p, oldSize, newSize);
	}
	goto LA1_;
	LA3_: ;
	{
		NI T6_;
		result = alignedAlloc__system_1865(newSize, align);
		copyMem__system_1709(result, p, oldSize);
		T6_ = (NI)0;
		T6_ = pluspercent___system_696(((NI) (ptrdiff_t) (result)), ((NI) (oldSize)));
		zeroMem__system_1706(((void*) (T6_)), ((NI) ((NI)(((NI) (newSize)) - ((NI) (oldSize))))));
		alignedDealloc(p, ((NI) (align)));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize, NI elemAlign) {
	void* result;
	NI headerSize;
	result = (void*)0;
	headerSize = align__system_1616(((NI) 4), elemAlign);
	{
		if (!(addlen <= ((NI) 0))) goto LA3_;
		result = p;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(p == NIM_NIL)) goto LA6_;
		result = newSeqPayload((NI)(len + addlen), elemSize, elemAlign);
	}
	goto LA1_;
	LA6_: ;
	{
		tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* p_2;
		NI oldCap;
		NI newCap;
		NI T9_;
		p_2 = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (p));
		oldCap = (NI)((*p_2).cap & ((NI) -1073741825));
		T9_ = (NI)0;
		T9_ = resize__system_2171(oldCap);
		newCap = ((T9_ >= (NI)(len + addlen)) ? T9_ : (NI)(len + addlen));
		{
			tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* q;
			void* T14_;
			NI T15_;
			NI T16_;
			if (!((NI)((*p_2).cap & ((NI) 1073741824)) == ((NI) 1073741824))) goto LA12_;
			T14_ = (void*)0;
			T14_ = alignedAlloc0__system_1891(((NI) ((NI)(headerSize + (NI)(elemSize * newCap)))), ((NI) (elemAlign)));
			q = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T14_));
			T15_ = (NI)0;
			T15_ = pluspercent___system_696(((NI) (ptrdiff_t) (q)), headerSize);
			T16_ = (NI)0;
			T16_ = pluspercent___system_696(((NI) (ptrdiff_t) (p_2)), headerSize);
			copyMem__system_1709(((void*) (T15_)), ((void*) (T16_)), ((NI) ((NI)(len * elemSize))));
			(*q).cap = newCap;
			result = ((void*) (q));
		}
		goto LA10_;
		LA12_: ;
		{
			NI oldSize;
			NI newSize;
			tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* q_2;
			void* T18_;
			oldSize = (NI)(headerSize + (NI)(elemSize * oldCap));
			newSize = (NI)(headerSize + (NI)(elemSize * newCap));
			T18_ = (void*)0;
			T18_ = alignedRealloc0__system_1911(((void*) (p_2)), ((NI) (oldSize)), ((NI) (newSize)), ((NI) (elemAlign)));
			q_2 = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T18_));
			(*q_2).cap = newCap;
			result = ((void*) (q_2));
		}
		LA10_: ;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZunicode_639)(tySequence__48JTohSgTy339bRxHzUD8KA* s, NI newlen) {
{	{
		NI T3_;
		T3_ = (*s).len;
		if (!(((NI) (newlen)) < T3_)) goto LA4_;
		shrink__pureZunicode_646(s, newlen);
	}
	goto LA1_;
	LA4_: ;
	{
		NI oldLen;
		NI T7_;
		tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg* xu;
		T7_ = (*s).len;
		oldLen = T7_;
		{
			if (!(((NI) (newlen)) <= oldLen)) goto LA10_;
			goto BeforeRet_;
		}
		LA10_: ;
		xu = ((tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg*) (s));
		{
			NIM_BOOL T14_;
			void* T18_;
			T14_ = (NIM_BOOL)0;
			T14_ = ((*xu).p == ((tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw*) NIM_NIL));
			if (T14_) goto LA15_;
			T14_ = ((*(*xu).p).cap < ((NI) (newlen)));
			LA15_: ;
			if (!T14_) goto LA16_;
			T18_ = (void*)0;
			T18_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), (NI)(((NI) (newlen)) - oldLen), ((NI) 4), ((NI) 4));
			(*xu).p = ((tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw*) (T18_));
		}
		LA16_: ;
		(*xu).len = ((NI) (newlen));
	}
	LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZunicode_3946)(tySequence__48JTohSgTy339bRxHzUD8KA* s, NI len) {
	shrink__pureZunicode_646(s, ((NI) 0));
	setLen__pureZunicode_639((&(*s)), len);
}
N_LIB_PRIVATE N_NIMCALL(tySequence__48JTohSgTy339bRxHzUD8KA, newSeq__pureZunicode_3958)(NI len) {
	tySequence__48JTohSgTy339bRxHzUD8KA result;
	result.len = 0; result.p = NIM_NIL;
	newSeq__pureZunicode_3946((&result), len);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZunicode_3967)(tySequence__48JTohSgTy339bRxHzUD8KA* x, NI32 value) {
	NI oldLen;
	NI T1_;
	tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg* xu;
	T1_ = (*x).len;
	oldLen = T1_;
	xu = ((tyObject_NimSeqV2__HYA9aJ4pmgLg0d25rS9cu9aIg*) (x));
	{
		NIM_BOOL T4_;
		void* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*xu).p == ((tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw*) NIM_NIL));
		if (T4_) goto LA5_;
		T4_ = ((*(*xu).p).cap < (NI)(oldLen + ((NI) 1)));
		LA5_: ;
		if (!T4_) goto LA6_;
		T8_ = (void*)0;
		T8_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), ((NI) 1), ((NI) 4), ((NI) 4));
		(*xu).p = ((tyObject_NimSeqPayload__pPF776WJm7EIoQXe2MSRzw*) (T8_));
	}
	LA6_: ;
	(*xu).len = (NI)(oldLen + ((NI) 1));
	(*(*xu).p).data[oldLen] = value;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len) {
	NimStringV2 result;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = ((NimStrPayload*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		NI colontmpD_;
		NimStrPayload* p;
		void* T6_;
		colontmpD_ = (NI)0;
		T6_ = (void*)0;
		T6_ = alloc0Impl__system_1727(((NI) ((NI)((NI)(len + ((NI) 1)) + ((NI) 4)))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = len;
		{
			if (!(((NI) 0) < len)) goto LA9_;
			copyMem__system_1709(((void*) ((&(*p).data[((NI) 0)]))), ((void*) (str)), ((NI) (len)));
		}
		LA9_: ;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD_ = len;
		result.len = colontmpD_;
		result.p = p;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	nimZeroMem((void*)(&colontmpD_), sizeof(NimStringV2));
	nimZeroMem((void*)(&colontmpD__2), sizeof(NimStringV2));
	{
		if (!(((void*) (str)) == NIM_NIL)) goto LA3_;
		colontmpD_ = toNimStr(str, ((NI) 0));
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = toNimStr(str, (str ? nimCStrLen(str) : 0));
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_2650)(NimStringV2* dest) {
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest).p);
}
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space) {
	NimStringV2 result;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(space <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = ((NimStrPayload*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		NimStrPayload* p;
		void* T6_;
		T6_ = (void*)0;
		T6_ = alloc0Impl__system_1727(((NI) ((NI)((NI)(space + ((NI) 1)) + ((NI) 4)))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = space;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = p;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(src.len + ((NI) 1)))));
		(*dest).len += src.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen) {
	NI newLen;
	newLen = (NI)((*s).len + addlen);
	{
		NIM_BOOL T3_;
		NimStrPayload* oldP;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((*s).p == ((NimStrPayload*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		oldP = (*s).p;
		T7_ = (void*)0;
		T7_ = alloc0Impl__system_1727(((NI) ((NI)((NI)(newLen + ((NI) 1)) + ((NI) 4)))));
		(*s).p = ((NimStrPayload*) (T7_));
		(*(*s).p).cap = newLen;
		{
			if (!(((NI) 0) < (*s).len)) goto LA10_;
			copyMem__system_1709(((void*) ((&(*(*s).p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((((*s).len <= newLen) ? (*s).len : newLen))));
		}
		LA10_: ;
	}
	goto LA1_;
	LA5_: ;
	{
		NI oldCap;
		oldCap = (NI)((*(*s).p).cap & ((NI) -1073741825));
		{
			NI newCap;
			NI T17_;
			void* T18_;
			if (!(oldCap < newLen)) goto LA15_;
			T17_ = (NI)0;
			T17_ = resize__system_2171(oldCap);
			newCap = ((newLen >= T17_) ? newLen : T17_);
			T18_ = (void*)0;
			T18_ = realloc0Impl__system_1734(((void*) ((*s).p)), ((NI) ((NI)((NI)(oldCap + ((NI) 1)) + ((NI) 4)))), ((NI) ((NI)((NI)(newCap + ((NI) 1)) + ((NI) 4)))));
			(*s).p = ((NimStrPayload*) (T18_));
			(*(*s).p).cap = newCap;
		}
		LA15_: ;
	}
	LA1_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	(*(*s).p).data[(NI)((*s).len + ((NI) 1))] = 0;
	(*s).len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, add__system_2856)(NimStringV2* x, NCSTRING y) {
	NI i;
	i = ((NI) 0);
	{
		if (!!((((void*) (y)) == NIM_NIL))) goto LA3_;
		{
			while (1) {
				if (!!(((NU8)(y[i]) == (NU8)(0)))) goto LA6;
				nimAddCharV1((&(*x)), y[i]);
				i += ((NI) 1);
			} LA6: ;
		}
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen) {
	{
		if (!(newLen == ((NI) 0))) goto LA3_;
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NIM_BOOL T8_;
			NIM_BOOL T10_;
			T8_ = (NIM_BOOL)0;
			T8_ = ((*s).len < newLen);
			if (T8_) goto LA9_;
			T10_ = (NIM_BOOL)0;
			T10_ = ((*s).p == ((NimStrPayload*) NIM_NIL));
			if (T10_) goto LA11_;
			T10_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
			LA11_: ;
			T8_ = T10_;
			LA9_: ;
			if (!T8_) goto LA12_;
			prepareAdd(s, (NI)(newLen - (*s).len));
		}
		LA12_: ;
		(*(*s).p).data[newLen] = 0;
	}
	LA1_: ;
	(*s).len = newLen;
}
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2312)(NimStringV2* s) {
	NimStrPayload* oldP;
	void* T1_;
	oldP = (*s).p;
	T1_ = (void*)0;
	T1_ = alloc0Impl__system_1727(((NI) ((NI)((NI)((*s).len + ((NI) 1)) + ((NI) 4)))));
	(*s).p = ((NimStrPayload*) (T1_));
	(*(*s).p).cap = (*s).len;
	copyMem__system_1709(((void*) ((&(*(*s).p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((NI)((*s).len + ((NI) 1)))));
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_180)(NimStringV2* result, NI x) {
	addInt__stdZprivateZdigitsutils_158(result, ((NI64) (x)));
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_3357)(tySequence__uB9b75OUPRENsBAu4AnoePA stackTraceEntries) {
	NimStringV2 result;
	tySequence__uB9b75OUPRENsBAu4AnoePA s;
	result.len = 0; result.p = NIM_NIL;
	s.len = 0; s.p = NIM_NIL;
	s = stackTraceEntries;
	result = rawNewString(((NI) 2000));
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T2_ = s.len;
		colontmp_ = (NI)(T2_ - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA4;
				i = res;
				{
					if (!(s.p->data[i].line == ((NI) -10))) goto LA7_;
					prepareAdd((&result), 17);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_3);
				}
				goto LA5_;
				LA7_: ;
				{
					if (!(s.p->data[i].line == ((NI) -100))) goto LA10_;
					prepareAdd((&result), 3);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_5);
				}
				goto LA5_;
				LA10_: ;
				{
					NI oldLenX60gensym118_;
					oldLenX60gensym118_ = result.len;
					add__system_2856((&result), s.p->data[i].filename);
					{
						if (!(((NI) 0) < s.p->data[i].line)) goto LA15_;
						prepareAdd((&result), 1);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_7);
						addInt__stdZprivateZdigitsutils_180((&result), s.p->data[i].line);
						{
							if (!NIM_FALSE) goto LA19_;
							prepareAdd((&result), 2);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_9);
							addInt__stdZprivateZdigitsutils_180((&result), ((NI) 0));
						}
						LA19_: ;
						prepareAdd((&result), 1);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_11);
					}
					LA15_: ;
					{
						NI kX60gensym118_;
						NI colontmp__2;
						NI res_2;
						kX60gensym118_ = (NI)0;
						colontmp__2 = (NI)0;
						colontmp__2 = ((((NI) 1) >= (NI)(((NI) 25) - (NI)(result.len - oldLenX60gensym118_))) ? ((NI) 1) : (NI)(((NI) 25) - (NI)(result.len - oldLenX60gensym118_)));
						res_2 = ((NI) 1);
						{
							while (1) {
								if (!(res_2 <= colontmp__2)) goto LA23;
								kX60gensym118_ = res_2;
								nimAddCharV1((&result), 32);
								res_2 += ((NI) 1);
							} LA23: ;
						}
					}
					add__system_2856((&result), s.p->data[i].procname);
					prepareAdd((&result), 1);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_13);
				}
				LA5_: ;
				res += ((NI) 1);
			} LA4: ;
		}
	}
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 4));
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc += ((NI) 8);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment) {
	NI hdrSize;
	NI T1_;
	hdrSize = align__system_1616(((NI) 4), alignment);
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), hdrSize);
	alignedDealloc(((void*) (T1_)), alignment);
}
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p) {
	TNimTypeV2** rti;
	rti = ((TNimTypeV2**) (p));
	{
		if (!!(((*(*rti)).destructor == NIM_NIL))) goto LA3_;
		((tyProc__4SVlZZPmetqBimNsH9cHcOA) ((*(*rti)).destructor))(p);
	}
	LA3_: ;
	nimRawDispose(p, (*(*rti)).align);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3245)(Exception** dest, Exception* src) {
	{
		if (!src) goto LA3_;
		nimIncRef(src);
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest));
		if (!T7_) goto LA8_;
		nimDestroyAndDispose((*dest));
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_3245(&currException__system_3202, (*currException__system_3202).up);
}
static N_INLINE(void, rawWriteString)(FILE* f, NCSTRING s, NI length) {
	size_t T1_;
	int T2_;
	T1_ = (size_t)0;
	T1_ = fwrite(((void*) (s)), ((size_t) 1), ((size_t) (length)), f);
	(void)(T1_);
	T2_ = (int)0;
	T2_ = fflush(f);
	(void)(T2_);
}
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__system_3167)(NCSTRING msg, NI length) {
	rawWriteString(stderr, msg, length);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3500);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__system_3172)(NCSTRING data, NI length) {
	NIM_BOOL toWrite;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	toWrite = NIM_TRUE;
	{
		NimStringV2 colontmpD_;
		if (!!((errorMessageWriter__system_3164 == NIM_NIL))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD_ = cstrToNimstr(data);
		errorMessageWriter__system_3164(colontmpD_);
		toWrite = NIM_FALSE;
		eqdestroy___system_2650((&colontmpD_));
		if (NIM_UNLIKELY(*nimErr_)) {
			LA5_:;
			{
				*nimErr_ = NIM_FALSE;
				popCurrentException();
				LA7_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!toWrite) goto LA11_;
		writeToStdErr__system_3167(data, length);
	}
	LA11_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledErrorAux__system_3386)(Exception* e) {
	tyArray__gpc2RrLEcWgv7ONpLYNHOw buf;
	NI L;
	nimZeroMem((void*)buf, sizeof(tyArray__gpc2RrLEcWgv7ONpLYNHOw));
	L = ((NI) 0);
	{
		NI T3_;
		NimStringV2 trace;
		T3_ = (*e).trace.len;
		if (!!((T3_ == ((NI) 0)))) goto LA4_;
		trace = dollar___system_3357((*e).trace);
		{
			if (!((NI)(L + trace.len) < ((NI) 2000))) goto LA8_;
			copyMem__system_1709(((void*) ((&buf[(L)- 0]))), ((void*) (nimToCStringConv(trace))), ((NI) (trace.len)));
			L += trace.len;
		}
		LA8_: ;
		eqdestroy___system_2650((&trace));
	}
	LA4_: ;
	{
		if (!((NI)(L + ((NI) 28)) < ((NI) 2000))) goto LA12_;
		copyMem__system_1709(((void*) ((&buf[(L)- 0]))), ((void*) ("Error: unhandled exception: ")), ((NI) 28));
		L += ((NI) 28);
	}
	LA12_: ;
	{
		if (!((NI)(L + (*e).message.len) < ((NI) 2000))) goto LA16_;
		copyMem__system_1709(((void*) ((&buf[(L)- 0]))), ((void*) (nimToCStringConv((*e).message))), ((NI) ((*e).message.len)));
		L += (*e).message.len;
	}
	LA16_: ;
	{
		if (!((NI)(L + ((NI) 2)) < ((NI) 2000))) goto LA20_;
		copyMem__system_1709(((void*) ((&buf[(L)- 0]))), ((void*) (" [")), ((NI) 2));
		L += ((NI) 2);
	}
	LA20_: ;
	{
		if (!((NI)(L + ((*e).name ? nimCStrLen((*e).name) : 0)) < ((NI) 2000))) goto LA24_;
		copyMem__system_1709(((void*) ((&buf[(L)- 0]))), ((void*) ((*e).name)), ((NI) (((*e).name ? nimCStrLen((*e).name) : 0))));
		L += ((*e).name ? nimCStrLen((*e).name) : 0);
	}
	LA24_: ;
	{
		if (!((NI)(L + ((NI) 2)) < ((NI) 2000))) goto LA28_;
		copyMem__system_1709(((void*) ((&buf[(L)- 0]))), ((void*) ("]\012")), ((NI) 2));
		L += ((NI) 2);
	}
	LA28_: ;
	{
		NimStringV2 T34_;
		if (!!((onUnhandledException__system_3385 == NIM_NIL))) goto LA32_;
		T34_.len = 0; T34_.p = NIM_NIL;
		T34_ = cstrToNimstr(((NCSTRING) (buf)));
		onUnhandledException__system_3385(T34_);
	}
	goto LA30_;
	LA32_: ;
	{
		showErrorMessage__system_3172(((NCSTRING) (buf)), L);
	}
	LA30_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__system_3489)(Exception* e) {
	{
		if (!!((unhandledExceptionHook__system_2847 == NIM_NIL))) goto LA3_;
		unhandledExceptionHook__system_2847(e);
	}
	LA3_: ;
	reportUnhandledErrorAux__system_3386(e);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3248)(Exception** dest, Exception* src) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimInErrorMode__system_3500;
		if (!(T3_)) goto LA4_;
		T3_ = !((currException__system_3202 == ((Exception*) NIM_NIL)));
		LA4_: ;
		if (!T3_) goto LA5_;
		reportUnhandledError__system_3489(currException__system_3202);
		eqsink___system_3248(&currException__system_3202, ((Exception*) NIM_NIL));
		exit(((NI) 1));
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats1dot6dot10atsnimatslibatssystemdotnim_Init000)(void) {
{
	initStackBottom();
}
}

