/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
#include <emscripten.h>
__attribute__((used)) NI calculateWidth(NCSTRING str, NIM_BOOL amb);
N_LIB_PRIVATE N_NIMCALL(NI, wcswidth__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_34)(NimStringV2 str, NIM_BOOL ambiguousIsWide);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_2650)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats1dot6dot10atsnimatslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
__attribute__((used)) NI calculateWidth(NCSTRING str, NIM_BOOL amb) {
	NI result;
	NimStringV2 colontmpD_;
	result = (NI)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(str);
	result = wcswidth__OOZOOZOOZOOZOnimbleZpkgs50Zwcwidth4548O49O51455049dbbf53565655a57f525450dcd5454b57c5649c51495451eb57edae5250Zwcwidth_34(colontmpD_, amb);
	eqdestroy___system_2650((&colontmpD_));
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats1dot6dot10atsnimatslibatssystemdotnim_Init000();
	PreMainInner();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	PreMain();
	NimMainInner();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

